package com.briup.apps.cms.bean;

public class ArticleCMSFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_file.id
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_file.article_id
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    private Long articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article_file.file_id
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    private String fileId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_file.id
     *
     * @return the value of cms_article_file.id
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_file.id
     *
     * @param id the value for cms_article_file.id
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_file.article_id
     *
     * @return the value of cms_article_file.article_id
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_file.article_id
     *
     * @param articleId the value for cms_article_file.article_id
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article_file.file_id
     *
     * @return the value of cms_article_file.file_id
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article_file.file_id
     *
     * @param fileId the value for cms_article_file.file_id
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }
}