package com.briup.apps.cms.bean;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value = "文章")
public class Article {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cms_article.id
	 *
	 * @mbg.generated Fri Sep 21 16:34:16 CST 2018
	 */
	@ApiModelProperty(value = "编号")
	private Long id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cms_article.title
	 *
	 * @mbg.generated Fri Sep 21 16:34:16 CST 2018
	 */
	@ApiModelProperty(value = "标题", required = true)
	private String title;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cms_article.listStyle
	 *
	 * @mbg.generated Fri Sep 21 16:34:16 CST 2018
	 */
	@ApiModelProperty(value = "列表样式", required = true)
	private String liststyle;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cms_article.publishTime
	 *
	 * @mbg.generated Fri Sep 21 16:34:16 CST 2018
	 */
	@ApiModelProperty(value = "发布时间")
	private String publishtime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cms_article.readTimes
	 *
	 * @mbg.generated Fri Sep 21 16:34:16 CST 2018
	 */
	@ApiModelProperty(value = "阅读次数")
	private Integer readtimes;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cms_article.status
	 *
	 * @mbg.generated Fri Sep 21 16:34:16 CST 2018
	 */
	@ApiModelProperty(value = "审核状态")
	private String status;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cms_article.thumbUp
	 *
	 * @mbg.generated Fri Sep 21 16:34:16 CST 2018
	 */
	@ApiModelProperty(value = "点赞次数")
	private Integer thumbup;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cms_article.thumbDown
	 *
	 * @mbg.generated Fri Sep 21 16:34:16 CST 2018
	 */
	@ApiModelProperty(value = "鄙视次数")
	private Integer thumbdown;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cms_article.music
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	@ApiModelProperty(value = "音乐地址")
	private String music;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cms_article.video
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	@ApiModelProperty(value = "视频地址")
	private String video;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cms_article.user_id
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	private Integer userId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column cms_article.category_id
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	private Long categoryId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cms_article.id
	 *
	 * @return the value of cms_article.id
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cms_article.id
	 *
	 * @param id
	 *            the value for cms_article.id
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cms_article.title
	 *
	 * @return the value of cms_article.title
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cms_article.title
	 *
	 * @param title
	 *            the value for cms_article.title
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cms_article.listStyle
	 *
	 * @return the value of cms_article.listStyle
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public String getListstyle() {
		return liststyle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cms_article.listStyle
	 *
	 * @param liststyle
	 *            the value for cms_article.listStyle
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public void setListstyle(String liststyle) {
		this.liststyle = liststyle == null ? null : liststyle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cms_article.publishTime
	 *
	 * @return the value of cms_article.publishTime
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public String getPublishtime() {
		return publishtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cms_article.publishTime
	 *
	 * @param publishtime
	 *            the value for cms_article.publishTime
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public void setPublishtime(String publishtime) {
		this.publishtime = publishtime == null ? null : publishtime.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cms_article.readTimes
	 *
	 * @return the value of cms_article.readTimes
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public Integer getReadtimes() {
		return readtimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cms_article.readTimes
	 *
	 * @param readtimes
	 *            the value for cms_article.readTimes
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public void setReadtimes(Integer readtimes) {
		this.readtimes = readtimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cms_article.status
	 *
	 * @return the value of cms_article.status
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cms_article.status
	 *
	 * @param status
	 *            the value for cms_article.status
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public void setStatus(String status) {
		this.status = status == null ? null : status.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cms_article.thumbUp
	 *
	 * @return the value of cms_article.thumbUp
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public Integer getThumbup() {
		return thumbup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cms_article.thumbUp
	 *
	 * @param thumbup
	 *            the value for cms_article.thumbUp
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public void setThumbup(Integer thumbup) {
		this.thumbup = thumbup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cms_article.thumbDown
	 *
	 * @return the value of cms_article.thumbDown
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public Integer getThumbdown() {
		return thumbdown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cms_article.thumbDown
	 *
	 * @param thumbdown
	 *            the value for cms_article.thumbDown
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public void setThumbdown(Integer thumbdown) {
		this.thumbdown = thumbdown;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cms_article.music
	 *
	 * @return the value of cms_article.music
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public String getMusic() {
		return music;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cms_article.music
	 *
	 * @param music
	 *            the value for cms_article.music
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public void setMusic(String music) {
		this.music = music == null ? null : music.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cms_article.video
	 *
	 * @return the value of cms_article.video
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public String getVideo() {
		return video;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cms_article.video
	 *
	 * @param video
	 *            the value for cms_article.video
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public void setVideo(String video) {
		this.video = video == null ? null : video.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cms_article.user_id
	 *
	 * @return the value of cms_article.user_id
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cms_article.user_id
	 *
	 * @param userId
	 *            the value for cms_article.user_id
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column cms_article.category_id
	 *
	 * @return the value of cms_article.category_id
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public Long getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column cms_article.category_id
	 *
	 * @param categoryId
	 *            the value for cms_article.category_id
	 *
	 * @mbg.generated Wed Sep 26 13:18:10 CST 2018
	 */
	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}
}