package com.briup.apps.cms.bean;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel(value="栏目")
public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.id
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
	@ApiModelProperty(value="编号")
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.name
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
	@ApiModelProperty(value="栏目名称",required=true)
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.comment
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
	@ApiModelProperty(value="备注",required=true)
    private String comment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.no
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
	@ApiModelProperty(value="序号",required=true)
    private Integer no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_category.parent_id
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
	@ApiModelProperty(value="父栏目编号")
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.id
     *
     * @return the value of cms_category.id
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.id
     *
     * @param id the value for cms_category.id
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.name
     *
     * @return the value of cms_category.name
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.name
     *
     * @param name the value for cms_category.name
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.comment
     *
     * @return the value of cms_category.comment
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.comment
     *
     * @param comment the value for cms_category.comment
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.no
     *
     * @return the value of cms_category.no
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.no
     *
     * @param no the value for cms_category.no
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_category.parent_id
     *
     * @return the value of cms_category.parent_id
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_category.parent_id
     *
     * @param parentId the value for cms_category.parent_id
     *
     * @mbg.generated Tue Sep 18 14:25:25 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}