package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.ArticleCMSFile;
import com.briup.apps.cms.bean.ArticleCMSFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArticleCMSFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_file
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    long countByExample(ArticleCMSFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_file
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    int deleteByExample(ArticleCMSFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_file
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_file
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    int insert(ArticleCMSFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_file
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    int insertSelective(ArticleCMSFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_file
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    List<ArticleCMSFile> selectByExample(ArticleCMSFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_file
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    ArticleCMSFile selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_file
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") ArticleCMSFile record, @Param("example") ArticleCMSFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_file
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    int updateByExample(@Param("record") ArticleCMSFile record, @Param("example") ArticleCMSFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_file
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    int updateByPrimaryKeySelective(ArticleCMSFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article_file
     *
     * @mbg.generated Tue Sep 18 14:39:31 CST 2018
     */
    int updateByPrimaryKey(ArticleCMSFile record);
}