package com.briup.apps.cms.dao;

import com.briup.apps.cms.bean.CMSFile;
import com.briup.apps.cms.bean.CMSFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CMSFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_file
     *
     * @mbg.generated Thu Sep 27 07:45:26 CST 2018
     */
    long countByExample(CMSFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_file
     *
     * @mbg.generated Thu Sep 27 07:45:26 CST 2018
     */
    int deleteByExample(CMSFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_file
     *
     * @mbg.generated Thu Sep 27 07:45:26 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_file
     *
     * @mbg.generated Thu Sep 27 07:45:26 CST 2018
     */
    int insert(CMSFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_file
     *
     * @mbg.generated Thu Sep 27 07:45:26 CST 2018
     */
    int insertSelective(CMSFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_file
     *
     * @mbg.generated Thu Sep 27 07:45:26 CST 2018
     */
    List<CMSFile> selectByExample(CMSFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_file
     *
     * @mbg.generated Thu Sep 27 07:45:26 CST 2018
     */
    CMSFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_file
     *
     * @mbg.generated Thu Sep 27 07:45:26 CST 2018
     */
    int updateByExampleSelective(@Param("record") CMSFile record, @Param("example") CMSFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_file
     *
     * @mbg.generated Thu Sep 27 07:45:26 CST 2018
     */
    int updateByExample(@Param("record") CMSFile record, @Param("example") CMSFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_file
     *
     * @mbg.generated Thu Sep 27 07:45:26 CST 2018
     */
    int updateByPrimaryKeySelective(CMSFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_file
     *
     * @mbg.generated Thu Sep 27 07:45:26 CST 2018
     */
    int updateByPrimaryKey(CMSFile record);
}